= General - Configuration Settings Get Sections
:toc: preamble

Used internally by the link:Config%20-%20Download%20Configuration.adoc[configuration download] and link:Operation%20-%20Generate%20Support%20File.adoc[generate support file] features to obtain the system section information `/api/edge/partial.json?struct={"system": null}` this allows you to access just a specific section of the configuration.

To get the full configuration you can use `/api/edge/partial.json`, `/api/edge/partial.json?struct=null` or `/api/edge/partial.json?struct={}`

== Request

=== Request Querystring

[cols="1,1,1,2", options="header"] 
|===
|Name
|Type
|Values
|Description

|`struct` (Optional)
|List (Object)
|JSON configuration
|The specific configuration sections requested.
|===

== Response

=== Root

[cols="1,1,1,2", options="header"] 
|===
|Name
|Type
|Values
|Description

|`SESSION_ID`
|String
|A session ID
|The authorisation string for this session that confirms the user is correctly authenticated.

|`GET`
|String
|JSON configuration
|The requested parent section.

|`success`
|Boolean
|`true` or `false`
|Whether the API request was successful.
|===

== Examples

=== Interfaces Example

.GET */api/edge/partial.json?struct={"interfaces": null}* Response
[source,json]
----
{"SESSION_ID": "742dfcc13b8d449aa36a4a1847bfcef7", "GET": {"interfaces": {"ethernet": {"eth0": {"address": ["dhcp"], "description": "WAN", "duplex": "auto", "firewall": {"in": {"name": "WAN_IN"}, "local": {"name": "WAN_LOCAL"}}, "speed": "auto"}, "eth1": {"address": ["192.168.0.254/24"], "description": "LAN", "duplex": "auto", "speed": "auto"}, "eth2": {"address": ["192.168.1.254/24"], "description": "LAN2", "duplex": "auto", "speed": "auto"}, "eth3": {"disable": null, "duplex": "auto", "speed": "auto"}}, "loopback": {"lo": null}}}, "success": true}
----