= Operation - Generate Support File
:toc: preamble

A support file can be generated by sending a HTTP POST to `/api/edge/operation/get-support-file.json` and then make an additional HTTP GET request to `/files/support-file/`.

The temporarily stored file will be deleted once the request has been made.

It does not support a HTTP GET.

This method is CSRF protected so also requires a `X-CSRF-TOKEN` (see link:../README.adoc#Sensitive-Requests-CSRF-Protection[Sensitive Requests (CSRF Protection)]).

== Response

=== Root

[cols="1,1,1,2", options="header"] 
|===
|Name
|Type
|Values
|Description

|`OPERATION`
|Object
|`OPERATION` object
|The saved support file information.

|`success`
|Boolean
|`true` or `false`
|Whether the API request was successful.
|===

=== `OPERATION` Object

[cols="1,1,1,2", options="header"] 
|===
|Name
|Type
|Values
|Description

|`path`
|String
|File path (e.g. `/tmp/sysd-save.ycYPpL`)
|A temporary file path on the local device where the support file was saved.

|`success`
|String
|A boolean encapsulated in a string (e.g. `"0"` or `"1"`)
|Whether the support file generation was successful.

|===

== Examples

=== Successful Save Response

.GET */api/edge/operation/get-support-file.json* Response
[source,json]
----
{"OPERATION": {"path": "/tmp/support_file.T2WQI5.tar.gz", "success": "1"}, "success": true}
----
