= Wizard - List All Wizards
:toc: preamble

A list of all the available wizards can be obtained by sending a HTTP GET to `/api/wizard/all.json`

== Response

=== Root

[cols="1,1,1,2", options="header"] 
|===
|Name
|Type
|Values
|Description

|`wizards`
|Object
|`wizards` object
|An object that contains the wizards.

|`success`
|Boolean
|`true` or `false`
|Whether the API request was successful.
|===

=== `wizards` Object

[cols="1,1,1,2", options="header"] 
|===
|Name
|Type
|Values
|Description

|`custom`
|Boolean
|`true` or `false`
|Whether the wizard is user defined.

|`type`
|String
|`"feature"` or `"setup"`
|Whether the wizard should be categorised as a configurable feature wizard or one used to setup the router.

|`id`
|String
|System ID
|The unique ID to refer to this wizard (typically `type`-`key`).

|`key`
|String
|Wizard key
|The unique wizard's key for its type.

|`name`
|String
|Wizard Name
|The name as it should appear in the web UI. 
|===


== Examples

=== Get All Wizards
.GET */api/wizard/all.json* Response
[source,json]
----
{"wizards": [{"custom": false, "type": "feature", "id": "feature-.Basic_Queue", "key": ".Basic_Queue", "name": ".Basic Queue"}, {"custom": false, "type": "feature", "id": "feature-.DDns", "key": ".DDns", "name": ".DDns"}, {"custom": false, "type": "feature", "id": "feature-.Port_Forwarding", "key": ".Port_Forwarding", "name": ".Port Forwarding"}, {"custom": false, "type": "feature", "id": "feature-.Sql", "key": ".Sql", "name": ".Sql"}, {"custom": false, "type": "feature", "id": "feature-.Vpn2", "key": ".Vpn2", "name": ".Vpn2"}, {"custom": false, "type": "setup", "id": "setup-Basic_Setup", "key": "Basic_Setup", "name": "Basic Setup"}, {"custom": false, "type": "feature", "id": "feature-DNS_host_names", "key": "DNS_host_names", "name": "DNS host names"}, {"custom": false, "type": "setup", "id": "setup-Load_Balancing", "key": "Load_Balancing", "name": "Load Balancing"}, {"custom": false, "type": "setup", "id": "setup-Load_Balancing2", "key": "Load_Balancing2", "name": "Load Balancing2"}, {"custom": false, "type": "setup", "id": "setup-Switch", "key": "Switch", "name": "Switch"}, {"custom": false, "type": "feature", "id": "feature-TCP_MSS_clamping", "key": "TCP_MSS_clamping", "name": "TCP MSS clamping"}, {"custom": false, "type": "feature", "id": "feature-UPnP", "key": "UPnP", "name": "UPnP"}, {"custom": false, "type": "feature", "id": "feature-VPN_status", "key": "VPN_status", "name": "VPN status"}, {"custom": false, "type": "setup", "id": "setup-WAN+2LAN", "key": "WAN+2LAN", "name": "WAN+2LAN"}, {"custom": false, "type": "setup", "id": "setup-WAN+2LAN2", "key": "WAN+2LAN2", "name": "WAN+2LAN2"}], "success": true}
----