= Statistics
:toc:

== Introduction

You can get streaming statistical data from the endpoint `wss://host-or-ip/ws/stats`. The data from the WebSocket is framed oddly, it's actually a streaming protocol that has been sent and received over WebSocket. The data will not arrive like you might expect. You *MUST* reassemble the web socket data fragments since the frames may not align with data boundaries. Commands must be sent with a valid `SESSION_ID`.

The format of data to and from the WebSocket stream is "LENGTH\nJSON_PAYLOAD". Failure of sending properly formed messages to start the streaming will result in no messages from server aka "dead air".

When the `SESSION_ID` times out the WebSocket will abruptly close so it's recommended to refresh it occasionally.

== Request Subscription

No data will be received by the socket until the user requests a subscription to a selection of message types:

[source,json]
----
249
{"SUBSCRIBE":[{"name":"export"},{"name":"discover"},{"name":"pon-stats"},{"name":"interfaces"},{"name":"system-stats"},{"name":"num-routes"},{"name":"config-change"},{"name":"users"}],"UNSUBSCRIBE":[],"SESSION_ID":"b5d5cfdb326c484abb00ca0d9effffff"}
----

Return values from the stream follow a similar format.

[source,json]
----
104
{
    "system-stats":
    {
        "cpu": "10",
        "uptime": "57864",
        "mem": "60"
    }
}
----

The web UI sends a non-standard ping every 30 seconds which consists of the following string with NO length prefix `{"CLIENT_PING"}`

== Subscription Types

=== JSON Based

Each one of these subscriptions will output data with the response being full JSON objects:

[cols="1,1,2", options="header"] 
|===
|Name
|Subscription String
|Description

|Configuration Change
|config-change
|Returns only when the config has changed as an indication you need to reload
`{'config-change': {'commit': 'started'}}` `{'config-change': {'commit': 'ended'}}`

|Device Discovery
|discover
|Results from any devices discovered via ubnt protocols.

|Traffic Analysis
|export
|Traffic Analysis (aka DPI) information.

|Interfaces
|interfaces
|Shows per-interface details about the device

|LLDP Neighbours
|lldp-detail
|Information about LLDP connected neighbours.

|System Statistics
|system-stats
|Returns cpu, memory and uptime
`{'system-stats': {'cpu': '35', 'mem': '22', 'uptime': '3321154'}}`

|Number of Routes
|num-routes
|Returns information about the number of active routes, use the json endpoint to fetch detailed routing information
`{'num-routes': {'connected': '5', 'static': '1', 'total': '6'}}`

|UDAPI Statistics
|udapi-statistics
|System information formatted for udapi, odd dialect

|Users
|users
|Lists the users logged into the EdgeOS device including ssh, web, and vpn
|===

=== RAW Console Output

Each one of these endpoints just dumps the raw console output data within a string `{'<<Request sub_id>>': '<line of text>\n' }`

These are subscribed to in the same way as the JSON subscriptions above but some additional parameters may need to be specified.

[cols="1,1,2", options="header"] 
|===
|Name
|Subscription String
|Description

|link:Raw%20-%20Bandwidth%20Test.adoc[Bandwidth Test]
|bwtest-feed
|Performs a bandwidth test.

|Log Messages
|log-feed
|Basically a `tail -f /var/log/messages`

|link:Raw%20-%20Firewall%20Statistics.adoc[Firewall Statistics]
|fw-stats
|Returns per-rule firewall stats.

|Port Forwarding Statistics
|pf-stats
|Contains the statistics from Port Forwarding.

|link:Raw%20-%20NAT%20Statistics.adoc[NAT Statistics]
|nat-stats
|Returns per-rule NAT stats.

|link:Raw%20-%20Ping.adoc[Ping]
|ping-feed
|Performs a ping.

|link:Raw%20-%20Traceroute.adoc[Traceroute]
|traceroute-feed
|Performs a traceroute.

|link:Raw%20-%20Traceroute.adoc[Packet Capture]
|packets-feed
|Performs a packet capture.
|===

=== Other Endpoints

There is also the following endpoints that not much is known about:

[cols="1,1,2", options="header"] 
|===
|Name
|Subscription String
|Description

|ONU List
|onu-list
|Lists Optical Network Unit devices.

|PON Statistics
|pon-stats
|Lists Passive Optical Network stats.

|NNI Statistics
|nni-stats
|Lists Network to Network Interface stats.
|===