= Statistics
:toc:

== Introduction

You can get streaming statistical data from the endpoint `wss://host-or-ip/ws/stats`. The data from the WebSocket is framed oddly, it's actually a streaming protocol that has been sent and received over WebSocket. The data will not arrive like you might expect. You *MUST* reassemble the web socket data fragments since the frames may not align with data boundaries. Commands must be sent with a valid `SESSION_ID`.

The format of data to and from the WebSocket stream is `LENGTH\nJSON_PAYLOAD`.

When the `SESSION_ID` times out the WebSocket will abruptly close so it's recommended to refresh it occasionally.

== Subscription Request

No data will be received by the socket until the user requests a subscription to a selection of message types:

[source,json]
----
249
{"SUBSCRIBE":[{"name":"export"},{"name":"discover"},{"name":"pon-stats"},{"name":"interfaces"},{"name":"system-stats"},{"name":"num-routes"},{"name":"config-change"},{"name":"users"}],"UNSUBSCRIBE":[],"SESSION_ID":"b5d5cfdb326c484abb00ca0d9effffff"}
----

Return values from the stream follow a similar format.

[source,json]
----
104
{
    "system-stats":
    {
        "cpu": "10",
        "uptime": "57864",
        "mem": "60"
    }
}
----

The web UI sends a ping every 30 seconds which consists of the following:

[source,json,subs="+quotes"]
----
66
{"CLIENT_PING":"","SESSION_ID":"*f989665499eb406b8600fd50bf1971bc*"}
----

[WARNING]
====
Failure to send a properly formed subscription request will continue to result in no messages being sent from the server.
====

== Subscription Types

=== JSON Based

Each one of these subscriptions will output data with the response being full JSON objects:

[cols="1,1,2", options="header"] 
|===
|Name
|Subscription String
|Description

|link:JSON%20-%20Configuration%20Change.adoc[Configuration Change]
|`config-change`
|Returns only when EdgeOS is processing a configuration change.

|link:JSON%20-%20Device%20Discovery.adoc[Device Discovery]
|`discover`
|Results from any devices discovered (typically via UBNT Discovery).

|link:JSON%20-%20Interfaces.adoc[Interfaces]
|`interfaces`
|Periodic messages containing network interface information for each of the EdgeOS network interfaces.

|link:JSON%20-%20Number%20Of%20Routes.adoc[Number Of Routes]
|`num-routes`
|Periodic messages containing counts of the EdgeOS network routes.

|link:JSON%20-%20System%20Statistics.adoc[System Statistics]
|`system-stats`
|Periodic messages containing system statistics about the EdgeOS device

|link:JSON%20-%20Traffic%20Analysis.adoc[Traffic Analysis]
|`export`
|Periodic messages containing Traffic Analysis (aka DPI) information.

|link:JSON%20-%20Users.adoc[Users]
|`users`
|Periodic messages listing the users logged into the EdgeOS device (including via SSH, Web and VPN).

|link:JSON%20-%20UDAPI%20Statistics.adoc[UDAPI Statistics]
|`udapi-statistics`
|Periodic messages containing device statistics in a specific API format, potentially used by UNMS.

|===

=== RAW Console Output (No Parameters)

Each one of these endpoints just dumps the raw console output data within a string `{'<<Request sub_id>>': '<line of text>\n' }`

These are subscribed to in the same way as the JSON subscriptions above but no additional parameters may need to be specified.

[cols="1,1,2", options="header"] 
|===
|Name
|Subscription String
|Description

|link:Raw%20-%20Log%20Feed.adoc[Log Feed]
|`log-feed`
|Basically a `tail -f /var/log/messages`

|link:Raw%20-%20NAT%20Statistics.adoc[NAT Statistics]
|`nat-stats`
|Returns per-rule NAT stats.

|link:Raw%20-%20Port%20Forwarding%20Statistics.adoc[Port Forwarding Statistics]
|`pf-stats`
|Contains the statistics from Port Forwarding.
|===

=== RAW Console Output (Parameters Required)

Each one of these endpoints just dumps the raw console output data within a string `{'<<Request sub_id>>': '<line of text>\n' }`

These are subscribed to in the same way as the JSON subscriptions above but some additional parameters may need to be specified.

[cols="1,1,2", options="header"] 
|===
|Name
|Subscription String
|Description

|link:Raw%20-%20Bandwidth%20Test.adoc[Bandwidth Test]
|`bwtest-feed`
|Performs or hosts a bandwidth test (using iperf).

|link:Raw%20-%20Firewall%20Statistics.adoc[Firewall Statistics]
|`fw-stats`
|Returns periodic firewall statistics.

|link:Raw%20-%20Ping.adoc[Ping]
|`ping-feed`
|Performs a ping.

|link:Raw%20-%20Traceroute.adoc[Traceroute]
|`traceroute-feed`
|Performs a tracert to trace a route to a host.

|link:Raw%20-%20Packet%20Capture.adoc[Packet Capture]
|`packets-feed`
|Performs a packet capture (using tcpdump).
|===

=== Other Endpoints

There are also the following endpoints that not much is known about (it's likely the implementation has been removed from `ubnt-util` but have been left over in the web UI):

[cols="1,1,2", options="header"] 
|===
|Name
|Subscription String
|Description

|LLDP Neighbours (not present in web UI)
|`lldp-detail`
|Information about Link Layer Discovery Protocol (LLDP) connected neighbours.

|NNI Statistics (not present in `ubnt-util`)
|`nni-stats`
|Lists Network to Network Interface (NNI) statistics.

|ONU List (not present in `ubnt-util`)
|`onu-list`
|Lists Optical Network Unit (ONU) details.

|PON Statistics (not present in `ubnt-util`)
|`pon-stats`
|Lists Passive Optical Network (PON) statistics.
|===