= EdgeOS API Guide
:toc: preamble

The EdgeOS API is largely undocumented. However as the requests and responses can be monitored in a web-browser a lot of information on how it works can be derived.

toc::[]

== Authentication

A HTTP POST to `\https://host-or-ip/` with the username and password encoded as a simple `application/x-www-form-urlencoded` form with the following request content will grant you a `PHPSESSID` cookie that is used to confirm you are authenticated:

[source,subs="+quotes"]
----
username=*USERNAME*&password=*PASSWORD*
----

This will return a HTTP status code `303 See Other` on success and the same login form again with a `200 OK` containing the text "The username or password you entered is incorrect" on failure, be careful as some web clients will automatically follow the 303 redirection and the cookies may not be where you expect them to be.

The session ID is returned multiple times but the only header of importance for authentication is:

[source,html]
----
Set-Cookie: PHPSESSID=9a00126c5bf04e29835f7c13fe5ab155; secure
----

[WARNING]
====
A session is valid for 15 minutes and is refreshed on every web request.

A session can be artificially extended with a link:REST%20API/General%20-%20Session%20Heartbeat.adoc[Session Heartbeat] request.
====

== REST API

=== General

* link:REST%20API/General%20-%20Batch%20Configuration.adoc[Batch Configuration]
* link:REST%20API/General%20-%20Get%20Complete%20Configuration.adoc[Get Complete Configuration]
* link:REST%20API/General%20-%20Get%20Configured%20Configuration%20Sections.adoc[Get Configured Configuration Sections]
* link:REST%20API/General%20-%20Get%20Data.adoc[Get Data]
* link:REST%20API/General%20-%20Session%20Heartbeat.adoc[Session Heartbeat]

=== Configuration

* link:REST%20API/Config%20-%20Download%20Configuration.adoc[Download Configuration]

=== Operations

* link:REST%20API/Operation%20-%20Check%20For%20Firmware%20Updates.adoc[Check For Firmware Updates]
* link:REST%20API/Operation%20-%20Clear%20Traffic%20Analysis.adoc[Clear Traffic Analysis]
* link:REST%20API/Operation%20-%20Generate%20Support%20File.adoc[Generate Support File]
* link:REST%20API/Operation%20-%20Reboot.adoc[Reboot]
* link:REST%20API/Operation%20-%20Release%20DHCP%20Lease.adoc[Release DHCP Lease]
* link:REST%20API/Operation%20-%20Renew%20DHCP%20Lease.adoc[Renew DHCP Lease]
* link:REST%20API/Operation%20-%20Reset%20Default%20Configuration.adoc[Reset Default Configuration]
* link:REST%20API/Operation%20-%20Shutdown.adoc[Shutdown]

= WebSocket

* link:WebSocket%20API/Command%20Line%20Interface%20%28CLI%29.adoc[Command Line Interface (CLI)]
* link:WebSocket%20API/Statistics.adoc[Statistics]

== Third Party Unofficial APIs

There are a few developers who have worked on creating unofficial APIs:

 * https://github.com/matthew1471/EdgeOS-API (written in C#)
 * https://github.com/andrewstuart/edgeos-rest (written in Go)