= EdgeOS API Guide
:toc: preamble

The EdgeOS API is not officially publicly documented. However as the requests and responses can be monitored in a web-browser along with the client-side JavaScript and Python back-end source code being available, a lot of information on how it works can be derived.

== Authentication

=== Login

A HTTP POST to `\https://host-or-ip/` with the username and password encoded as a simple `application/x-www-form-urlencoded` form as the request content will grant you a `PHPSESSID` cookie that is used to confirm you are authenticated:

[source,subs="+quotes"]
----
username=*USERNAME*&password=*PASSWORD*
----

This will return a HTTP status code `303 See Other` with a selection of cookies on success. On failure, a `200 OK` is returned with the same login form again, only this time containing the text `The username or password you entered is incorrect`. 

[NOTICE]
=====
Be careful as some web clients will automatically follow the 303 redirection and therefore the cookies may not be where you expect them to be.
=====

==== Session ID

The session ID is returned multiple times in the header but the primary header for proving successful authentication is:

[source,http,subs="+quotes"]
----
Set-Cookie: PHPSESSID=*9a00126c5bf04e29835f7c13fe5ab155*; secure
----

[WARNING]
====
A session is valid for 1440 seconds (24 minutes) and is refreshed on every web request.

A session can be periodically artificially extended with a link:REST%20API/General%20-%20Session%20Heartbeat.adoc[Session Heartbeat] request.
====

Although this appears to be a PHP generated session ID, the backend was switched from PHP to a Python process in EdgeRouter firmware v1.9.7. Sessions are now generated by link:https://beaker.readthedocs.io/[Beaker] (`/usr/lib/python2.7/dist-packages/beaker.session.py`) using Python's `uuid.uuid4().hex` function to create a 32 character (128-bit) hexadecimal string uuid (this is invoked by the web GUI's `views.py` function `login()`).

==== Session Store

For the session store, the full session details and variables are converted from a Python serialised object to one generated by `phpserialize` (due to `ses-mon.cpp` 's reliance on the older PHP style backend for session storage apparently) and are stored in the path `/var/run/beaker/container_file`.

==== Sensitive Requests (CSRF Protection)

To be able to call sensitive methods (anything that is not a `GET`, `HEAD`, `OPTIONS` or `TRACE` request and where the protection is not otherwise explicitly disabled or it is otherwise permitted to turn off protection for requests with the `X-Requested-With` client header set) a `X-CSRF-TOKEN` need also be supplied in the request (EdgeOS currently allows this in the querystring and does not mandate this is set as a cookie). This is a 64 character (256-bit) hexadecimal string generated using Python's `os.urandom()`.

[source,http,subs="+quotes"]
----
Set-Cookie: X-CSRF-TOKEN=521b05cab373afb31d4c84f521cc1a8afc2dac12288d90e14120fce280d5fcdd
----

=== Logout

A HTTP GET to `/logout` will end the current session.

== REST API

The REST API is served from `/var/www/python/edgeos_gui/api` on the EdgeOS device.

=== Edge - General

* link:REST%20API/General%20-%20Authenticate.adoc[Authenticate]
* link:REST%20API/General%20-%20Configuration%20Settings%20Batch.adoc[Configuration Settings Batch]
* link:REST%20API/General%20-%20Configuration%20Settings%20Delete.adoc[Configuration Settings Delete]
* link:REST%20API/General%20-%20Configuration%20Settings%20Get%20Predefined%20List.adoc[Configuration Settings Get Predefined List]
* link:REST%20API/General%20-%20Configuration%20Settings%20Get%20Sections.adoc[Configuration Settings Get Sections]
* link:REST%20API/General%20-%20Configuration%20Settings%20Get%20Tree.adoc[Configuration Settings Get Tree]
* link:REST%20API/General%20-%20Configuration%20Settings%20Set.adoc[Configuration Settings Set]
* link:REST%20API/General%20-%20Get%20Data.adoc[Get Data]
* link:REST%20API/General%20-%20Session%20Heartbeat.adoc[Session Heartbeat]
* link:REST%20API/General%20-%20Upgrade%20Firmware.adoc[Upgrade Firmware]
* link:REST%20API/General%20-%20Wizard%20Feature.adoc[Wizard Feature]
* link:REST%20API/General%20-%20Wizard%20Setup.adoc[Wizard Setup]

=== Edge - Configuration

* link:REST%20API/Config%20-%20Download%20Configuration.adoc[Download Configuration]
* link:REST%20API/Config%20-%20Restore%20Configuration.adoc[Restore Configuration]

=== Edge - Optical Network Unit (ONU)

* Reboot
* Upgrade

=== Edge - Operations

These are defined as "<op>.json" and are passed to the closed-source `ubnt-util`:

* link:REST%20API/Operation%20-%20Check%20For%20Firmware%20Updates.adoc[Check For Firmware Updates]
* link:REST%20API/Operation%20-%20Clear%20Traffic%20Analysis.adoc[Clear Traffic Analysis]
* link:REST%20API/Operation%20-%20Generate%20Support%20File.adoc[Generate Support File]
* link:REST%20API/Operation%20-%20Reboot.adoc[Reboot]
* link:REST%20API/Operation%20-%20Release%20DHCP%20Lease.adoc[Release DHCP Lease]
* link:REST%20API/Operation%20-%20Renew%20DHCP%20Lease.adoc[Renew DHCP Lease]
* link:REST%20API/Operation%20-%20Reset%20Default%20Configuration.adoc[Reset Default Configuration]
* link:REST%20API/Operation%20-%20Shutdown.adoc[Shutdown]

=== Optical Line Terminal (OLT) - General

* Get Connected Optical Network Unit (ONU) Devices

=== Optical Line Terminal (OLT) - Optical Network Unit (ONU)

* link:REST%20API/ONU%20-%20Generate%20Support%20File.adoc[Generate Support File]
* Get Connected WiFi Clients
* Locate
* Reset

=== Wizards

* link:REST%20API/Wizard%20-%20List%20All%20Wizards.adoc[List All Wizards]
* [.line-through]#Runtime# (referenced in the web UI but is no longer present)
* [.line-through]#Setup# (referenced in the web UI but is no longer present)
* link:REST%20API/Wizard%20-%20Specific%20Wizard%20Create.adoc[Specific Wizard Create]
* link:REST%20API/Wizard%20-%20Specific%20Wizard%20Download.adoc[Specific Wizard Download]
* link:REST%20API/Wizard%20-%20Specific%20Wizard%20Remove.adoc[Specific Wizard Remove]
* link:REST%20API/Wizard%20-%20Specific%20Wizard%20Upload.adoc[Specific Wizard Upload]

== WebSocket API

* link:WebSocket%20API/Command%20Line%20Interface%20%28CLI%29.adoc[Command Line Interface (CLI)]
* link:WebSocket%20API/Statistics.adoc[Statistics]

== Third Party Unofficial API Wrappers

There are a few developers who have worked on creating unofficial API wrappers:

 * https://github.com/matthew1471/EdgeOS-API (written in C#)
 * https://github.com/brontide/aioedgeos (written in Python)
 * https://github.com/andrewstuart/edgeos-rest (written in Go)